name = "drive-mate"
main = "functions/worker.ts"
compatibility_date = "2026-05-23"
workers_dev = true

[assets]
directory = "dist/drive-mate/browser"
binding = "ASSETS"
not_found_handling = "single-page-application"

[placement]
mode = "smart"
